name: Auto approve

on: pull_request_target

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    if: >-
      github.actor == 'dependabot[bot]' ||
      github.actor == 'BaiqingL' ||
      github.actor == 'JoyboyBrian' ||
      github.actor == 'JakeTrock' ||
      github.actor == 'allenlinsh' ||
      github.actor == 'mathewjhan' ||
      github.actor == 'pandyamarut' ||
      github.actor == 'artem-osmosis'
    steps:
      - uses: hmarr/auto-approve-action@v4
